### ISSUE TITLE
How to build this query?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#29]
Hi!
```
SELECT message . *
FROM (
SELECT MAX( id ) AS  'maxid', IF(  `to_id` =1,  `from_id` ,  `to_id` ) AS  'user', SUM(`status`='unread') AS count
FROM message
WHERE  `from_id` =1
OR  `to_id` =1
GROUP BY user
) AS a
INNER JOIN message ON a.maxid = id
ORDER BY id DESC
LIMIT 0 , 50
```

**Comment by qiangxue** [comment]
Query builder currently doesn't support building queries with sub-queries. You will need to build the sub-query first. Get its query SQL and use it as the `From` to build the outer SQL.

Since this may not be very straightforward, I would recommend you write SQLs directly for better clarity of your code.
